subject_categories = {
    'artichoke': 'Artichoke',
    'baked_goods': 'Baked goods',
    'big_dishes': 'Serving dishes',
    'bottles': 'Bottles',
    'bread': 'Bread',
    'burgers': 'Burgers',
    'cakes': 'Cakes',
    'cheese': 'Cheese',
    'coffee': 'Coffee',
    'confectionery': 'Confectionery',
    'cornucopia': 'Cornucopia',
    'doughnuts': 'Doughnuts',
    'drinks': 'Drinks',
    'fish': 'Fish',
    'flowers': 'Flowers',
    'fruit': 'Fruit',
    'giant_lemons': 'Giant lemons',
    'hot_cross': 'Hot Cross',
    'juices': 'Juices',
    'lettuce': 'Lettuce',
    'macarons': 'Macarons',
    'market_architecture': 'Market architecture',
    'market_scenes': 'Market scenes',
    'meat': 'Meat',
    'meringue': 'Meringue',
    'mushroom_basket': 'Mushroom basket',
    'mushrooms': 'Mushrooms',
    'olives': 'Olives',
    'oranges': 'Oranges',
    'other_shard': 'Other shard shots',
    'oysters': 'Oysters',
    'pasta': 'Pasta',
    'people_eating': 'People eating',
    'people_holding_produce': 'People holding produce',
    'people': 'People',
    'rainbow_chard': 'Rainbow chard',
    'restaurant_food': 'Restaurant food',
    'romanesco_cabbage': 'Romanesco cabbage',
    'roof_and_shard': 'Roof and shard',
    'scotch_egg': 'Scotch Egg',
    'signage': 'Signage',
    'spices': 'Spices',
    'store_front': 'Store-front',
    'strawberries': 'Strawberries',
    'street_art': 'Street Art',
    'takeaway_food': 'Takeaway Food',
    'tomatoes': 'Tomatoes',
    'us_at_the_market': 'Us at the market',
    'vegetables': 'Vegetables'
}

style_categories = {
    'loads_of_the_same_thing': 'Loads of the same thing',
    'in_rows': 'In rows',
    'shot_from_above': 'Shot from above',
    'food_in_hand': 'Food in hand',
    'ultra_close_ups': 'Ultra close-ups'
}